// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// User Listing
export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAILURE = 'USERS_FAILURE';

// Permissions Listing
export const FETCH_PERMISSIONS_REQUEST = 'FETCH_PERMISSIONS_REQUEST';
export const FETCH_PERMISSIONS_SUCCESS = 'FETCH_PERMISSIONS_SUCCESS';
export const FETCH_PERMISSIONS_FAILURE = 'FETCH_PERMISSIONS_FAILURE';


// User Creation
export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_FAILURE = 'USER_CREATE_FAILURE';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';

// Grant Permissions
export const GRANT_PERMISSION_REQUEST = 'GRANT_PERMISSION_REQUEST';
export const GRANT_PERMISSION_FAILURE = 'GRANT_PERMISSION_FAILURE';
export const GRANT_PERMISSION_SUCCESS = 'GRANT_PERMISSION_SUCCESS';
