// Signup
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// User Listing
export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAILURE = 'USERS_FAILURE';

// Permissions Listing
export const FETCH_PERMISSIONS_REQUEST = 'FETCH_PERMISSIONS_REQUEST';
export const FETCH_PERMISSIONS_SUCCESS = 'FETCH_PERMISSIONS_SUCCESS';
export const FETCH_PERMISSIONS_FAILURE = 'FETCH_PERMISSIONS_FAILURE';

// User Creation
export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_FAILURE = 'USER_CREATE_FAILURE';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';

// Edit User
export const USER_EDIT_REQUEST = 'USER_EDIT_REQUEST';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
export const USER_EDIT_FAILURE = 'USER_EDIT_FAILURE';

// User Detail
export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST';
export const USER_DETAIL_FAILURE = 'USER_DETAIL_FAILURE';
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';

// User Delete
export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DETAIL_SUCCESS';
export const USER_DELETE_FAILURE = 'USER_DELETE_FAILURE';

// Grant Permissions
export const GRANT_PERMISSION_REQUEST = 'GRANT_PERMISSION_REQUEST';
export const GRANT_PERMISSION_FAILURE = 'GRANT_PERMISSION_FAILURE';
export const GRANT_PERMISSION_SUCCESS = 'GRANT_PERMISSION_SUCCESS';

// Revoke Permissions
export const REVOKE_PERMISSION_REQUEST = 'REVOKE_PERMISSION_REQUEST';
export const REVOKE_PERMISSION_SUCCESS = 'REVOKE_PERMISSION_SUCCESS';
export const REVOKE_PERMISSION_FAILURE = 'REVOKE_PERMISSION_FAILURE';

// Subject Creation
export const SUBJECT_CREATE_REQUEST = 'SUBJECT_CREATE_REQUEST';
export const SUBJECT_CREATE_FAILURE = 'SUBJECT_CREATE_FAILURE';
export const SUBJECT_CREATE_SUCCESS = 'SUBJECT_CREATE_SUCCESS';

// Subject Listing
export const SUBJECT_LISTING_REQUEST = 'SUBJECT_LISTING_REQUEST';
export const SUBJECT_LISTING_FAILURE = 'SUBJECT_LISTING_FAILURE';
export const SUBJECT_LISTING_SUCCESS = 'SUBJECT_LISTING_SUCCESS';

// Subject Detail
export const SUBJECT_DETAIL_REQUEST = 'SUBJECT_DETAIL_REQUEST';
export const SUBJECT_DETAIL_SUCCESS = 'SUBJECT_DETAIL_SUCCESS';
export const SUBJECT_DETAIL_FAILURE = 'SUBJECT_DETAIL_FAILURE';

// Subject Editing
export const SUBJECT_EDIT_REQUEST = 'SUBJECT_EDIT_REQUEST';
export const SUBJECT_EDIT_SUCCESS = 'SUBJECT_EDIT_SUCCESS';
export const SUBJECT_EDIT_FAILURE = 'SUBJECT_EDIT_FAILURE';

// Subject Deletion
export const SUBJECT_DELETE_REQUEST = 'SUBJECT_DELETE_REQUEST';
export const SUBJECT_DELETE_SUCCESS = 'SUBJECT_DELETE_SUCCESS';
export const SUBJECT_DELETE_FAILURE = 'SUBJECT_DELETE_FAILURE';

// Lesson Listing
export const LESSON_LISTING_REQUEST = 'LESSON_LISTING_REQUEST';
export const LESSON_LISTING_FAILURE = 'LESSON_LISTING_FAILURE';
export const LESSON_LISTING_SUCCESS = 'LESSON_LISTING_SUCCESS';

// Lessons Taught Listing
export const LESSON_TAUGHT_LISTING_REQUEST = 'LESSON_TAUGHT_LISTING_REQUEST';
export const LESSON_TAUGHT_LISTING_FAILURE = 'LESSON_TAUGHT_LISTING_FAILURE';
export const LESSON_TAUGHT_LISTING_SUCCESS = 'LESSON_TAUGHT_LISTING_SUCCESS';

// Lesson Creation
export const LESSON_CREATE_REQUEST = 'LESSON_CREATE_REQUEST';
export const LESSON_CREATE_FAILURE = 'LESSON_CREATE_FAILURE';
export const LESSON_CREATE_SUCCESS = 'LESSON_CREATE_SUCCESS';

// Lesson Detail
export const LESSON_DETAIL_REQUEST = 'LESSON_DETAIL_REQUEST';
export const LESSON_DETAIL_FAILURE = 'LESSON_DETAIL_FAILURE';
export const LESSON_DETAIL_SUCCESS = 'LESSON_DETAIL_SUCCESS';

// Lesson Edit
export const LESSON_EDIT_REQUEST = 'LESSON_EDIT_REQUEST';
export const LESSON_EDIT_FAILURE = 'LESSON_EDIT_FAILURE';
export const LESSON_EDIT_SUCCESS = 'LESSON_EDIT_SUCCESS';

// Lesson Deletion
export const LESSON_DELETE_REQUEST = 'LESSON_DELETE_REQUEST';
export const LESSON_DELETE_SUCCESS = 'LESSON_DELETE_SUCCESS';
export const LESSON_DELETE_FAILURE = 'LESSON_DELETE_FAILURE';

// Assign Essay
export const ASSIGN_ESSAY_REQUEST = 'ASSIGN_ESSAY_REQUEST';
export const ASSIGN_ESSAY_FAILURE = 'ASSIGN_ESSAY_FAILURE';
export const ASSIGN_ESSAY_SUCCESS = 'ASSIGN_ESSAY_SUCCESS';

// Assign Quiz
export const ASSIGN_QUIZ_REQUEST = 'ASSIGN_QUIZ_REQUEST';
export const ASSIGN_QUIZ_FAILURE = 'ASSIGN_QUIZ_FAILURE';
export const ASSIGN_QUIZ_SUCCESS = 'ASSIGN_QUIZ_SUCCESS';


// Fetch Current User details
export const FETCH_CURRENT_USER_DETAILS_REQUEST = 'FETCH_CURRENT_USER_DETAILS_REQUEST';
export const FETCH_CURRENT_USER_DETAILS_FAILURE = 'FETCH_CURRENT_USER_DETAILS_FAILURE';
export const FETCH_CURRENT_USER_DETAILS_SUCCESS = 'FETCH_CURRENT_USER_DETAILS_SUCCESS';
export const REMOVE_CURRENT_USER_DETAILS = 'REMOVE_CURRENT_USER_DETAILS';

// Homework due
export const HOMEWORK_DUE_REQUEST = 'HOMEWORK_DUE_REQUEST';
export const HOMEWORK_DUE_SUCCESS = 'HOMEWORK_DUE_SUCCESS';
export const HOMEWORK_DUE_FAILURE = 'HOMEWORK_DUE_FAILURE';

// Essay Detail
export const FETCH_ESSAY_REQUEST = 'FETCH_ESSAY_REQUEST';
export const FETCH_ESSAY_SUCCESS = 'FETCH_ESSAY_SUCCESS';
export const FETCH_ESSAY_FAILURE = 'FETCH_ESSAY_FAILURE';

// Quiz Detail
export const FETCH_QUIZ_REQUEST = 'FETCH_QUIZ_REQUEST';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_FAILURE = 'FETCH_QUIZ_FAILURE';

// Submit Essay
export const SUBMIT_ESSAY_REQUEST = 'SUBMIT_ESSAY_REQUEST';
export const SUBMIT_ESSAY_SUCCESS = 'SUBMIT_ESSAY_SUCCESS';
export const SUBMIT_ESSAY_FAILURE = 'SUBMIT_ESSAY_FAILURE';

// Submit Quiz
export const SUBMIT_QUIZ_REQUEST = 'SUBMIT_QUIZ_REQUEST';
export const SUBMIT_QUIZ_SUCCESS = 'SUBMIT_QUIZ_SUCCESS';
export const SUBMIT_QUIZ_FAILURE = 'SUBMIT_QUIZ_FAILURE';

// Fetch Submissions
export const FETCH_SUBMISSIONS_REQUEST = 'FETCH_SUBMISSIONS_REQUEST';
export const FETCH_SUBMISSIONS_FAILURE = 'FETCH_SUBMISSIONS_FAILURE';
export const FETCH_SUBMISSIONS_SUCCESS = 'FETCH_SUBMISSIONS_SUCCESS';

// Fetch Essay Submission
export const FETCH_ESSAY_SUBMISSION_REQUEST = 'FETCH_ESSAY_SUBMISSION_REQUEST';
export const FETCH_ESSAY_SUBMISSION_FAILURE = 'FETCH_ESSAY_SUBMISSION_FAILURE';
export const FETCH_ESSAY_SUBMISSION_SUCCESS = 'FETCH_ESSAY_SUBMISSION_SUCCESS';

// Fetch Quiz Submission
export const FETCH_QUIZ_SUBMISSION_REQUEST = 'FETCH_QUIZ_SUBMISSION_REQUEST';
export const FETCH_QUIZ_SUBMISSION_FAILURE = 'FETCH_QUIZ_SUBMISSION_FAILURE';
export const FETCH_QUIZ_SUBMISSION_SUCCESS = 'FETCH_QUIZ_SUBMISSION_SUCCESS';

// Comment Create
export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST';
export const COMMENT_CREATE_FAILURE = 'COMMENT_CREATE_FAILURE';
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS';
